document.writeln("<div class=\'d-none d-lg-block col-lg-3\'>");
document.writeln("	<ul class=\'nav nav-pills nav-vertical\'>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'../docs/index.html\' class=\'nav-link\'>");
document.writeln("		  介绍");
document.writeln("		</a>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-base\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  基础功能");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-base\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  数组行列互换");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  对象深拷贝");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-datasource\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  数据源");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-datasource\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  CSV文件");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  串口数据");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  图像");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  视频");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-draw_graph\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  图表");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-draw_graph\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  二维图表");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  三维图表");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-math_theory\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  数学理论");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-math_theory\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  交集");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  并集");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-base_math\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  基础数学");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-base_math\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  ...");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-disperse_math\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  离散数学");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-disperse_math\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  ...");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-apply_math\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  应用数学");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-apply_math\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  ...");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	  <li class=\'nav-item\'>");
document.writeln("		<a href=\'#menu-combination_apply\' class=\'nav-link\' data-bs-toggle=\'collapse\' aria-expanded=\'false\'>");
document.writeln("		  组合应用");
document.writeln("		  <span class=\'nav-link-toggle\'></span>");
document.writeln("		</a>");
document.writeln("		<ul class=\'nav nav-pills collapse\' id=\'menu-combination_apply\'>");
document.writeln("		  <li class=\'nav-item\'>");
document.writeln("			<a href=\'\' class=\'nav-link\'>");
document.writeln("			  ...");
document.writeln("			</a>");
document.writeln("		  </li>");
document.writeln("		</ul>");
document.writeln("	  </li>");
document.writeln("	</ul>");
document.writeln("  </div>");