document.writeln("<header id=\'html_header\' class=\'navbar-expand-md\'>");
document.writeln("	<div class=\'collapse navbar-collapse\' id=\'navbar-menu\'>");
document.writeln("	  <div class=\'navbar navbar-light\'>");
document.writeln("		<div class=\'container-xl\'>");
document.writeln("		  <ul class=\'navbar-nav\'>");
document.writeln("			<li class=\'nav-item\'>");
document.writeln("			  <a class=\'nav-link\' href=\'" + p_path + "/index.html\' >");
document.writeln("				<span class=\'nav-link-icon d-md-none d-lg-inline-block\'>");
document.writeln("				  <svg xmlns=\'http://www.w3.org/2000/svg\' class=\'icon\' width=\'24\' height=\'24\' viewBox=\'0 0 24 24\' stroke-width=\'2\' stroke=\'currentColor\' fill=\'none\' stroke-linecap=\'round\' stroke-linejoin=\'round\'><path stroke=\'none\' d=\'M0 0h24v24H0z\' fill=\'none\'/><path d=\'M5 12l-2 0l9 -9l9 9l-2 0\' /><path d=\'M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7\' /><path d=\'M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6\' /></svg>");
document.writeln("				</span>");
document.writeln("				<span class=\'nav-link-title\'>");
document.writeln("				  首页");
document.writeln("				</span>");
document.writeln("			  </a>");
document.writeln("			</li>");
document.writeln("			<li class=\'nav-item\'>");
document.writeln("			  <a class=\'nav-link\' href=\'" + p_path + "/docs/index.html\' >");
document.writeln("				<span class=\'nav-link-icon d-md-none d-lg-inline-block\'>");
document.writeln("				  <svg xmlns=\'http://www.w3.org/2000/svg\' class=\'icon\' width=\'24\' height=\'24\' viewBox=\'0 0 24 24\' stroke-width=\'2\' stroke=\'currentColor\' fill=\'none\' stroke-linecap=\'round\' stroke-linejoin=\'round\'><path stroke=\'none\' d=\'M0 0h24v24H0z\' fill=\'none\'/><path d=\'M12 12m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\' /><path d=\'M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0\' /><path d=\'M15 15l3.35 3.35\' /><path d=\'M9 15l-3.35 3.35\' /><path d=\'M5.65 5.65l3.35 3.35\' /><path d=\'M18.35 5.65l-3.35 3.35\' /></svg>");
document.writeln("				</span>");
document.writeln("				<span class=\'nav-link-title\'>");
document.writeln("				  文档");
document.writeln("				</span>");
document.writeln("			  </a>");
document.writeln("			</li>");
document.writeln("		  </ul>");
document.writeln("		</div>");
document.writeln("	  </div>");
document.writeln("	</div>");
document.writeln("  </header>");